import Link from "next/link";
import Image from "next/image";

const capabilities = [
  ["01", "Acquire", "We look for properties where sound fundamentals and a clear thesis create room for long-term value.", "/what-we-do/acquisitions"],
  ["02", "Transform", "We plan thoughtful improvements that respond to the property, its market, and the people who use it.", "/what-we-do/renovation"],
  ["03", "Operate", "We consider ownership, rental economics, and operating discipline from the start.", "/what-we-do/operations"],
  ["04", "Partner", "We work alongside owners, investors, lenders, agents, and local specialists.", "/what-we-do/partnerships"]
];

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-image"><Image src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2400&q=88" alt="Sunlit modern interior with warm natural materials" fill priority sizes="100vw"/></div><div className="hero-wash"/><div className="hero-content page-wrap"><div className="eyebrow eyebrow-light"><span/> REAL ESTATE · INVESTMENT · INTELLIGENCE</div><h1>Building value<br/>through <em>real estate.</em></h1><p className="hero-sub">We acquire, improve, and operate real estate through disciplined investing, market intelligence, and technology.</p><div className="hero-actions"><Link href="/sell-your-property" className="button button-cream">Sell your property <span>↗</span></Link><Link href="/portfolio" className="button button-outline-light">Explore our properties</Link></div><Link className="hero-text-link" href="/about">Our investment approach <span>↓</span></Link></div><div className="hero-caption"><span>BUILT WITH INTENTION</span><span>01 — 04</span></div></section>
    <section className="intro-section section-pad"><div className="page-wrap intro-grid"><div><p className="eyebrow">A CLEARER POINT OF VIEW</p><h2>Real estate is local.<br/><em>Our thinking is rigorous.</em></h2></div><div className="intro-copy"><p className="lead">We believe good investment decisions begin with asking better questions about the property, its market, and what it could become.</p><p>Stable & Noble Properties brings a disciplined approach to acquisition, improvement, and operations. We combine property-level diligence with market context to understand the opportunity before deciding how to act.</p><Link href="/about" className="text-link">Meet Stable & Noble <span>↗</span></Link></div></div></section>
    <section className="approach-section section-pad"><div className="page-wrap"><div className="section-heading"><div><p className="eyebrow">OUR CAPABILITIES</p><h2>One property.<br/><em>A considered plan.</em></h2></div><p>From first look to long-term stewardship, each decision is informed by the realities of the asset and the objectives behind it.</p></div><div className="capability-grid">{capabilities.map(([n,title,copy,href])=><Link href={href} key={title} className="capability-card"><span className="cap-number">{n}</span><span className="cap-arrow">↗</span><h3>{title}</h3><p>{copy}</p><span className="card-line"/></Link>)}</div></div></section>
    <section className="data-section"><div className="data-photo"><Image src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85" alt="Architectural residence framed by native landscaping" fill sizes="(max-width: 800px) 100vw, 48vw"/></div><div className="data-content"><p className="eyebrow eyebrow-light">A BETTER INFORMED DECISION</p><h2>Real estate.<br/><em>Informed by data.</em></h2><p>We bring property expertise together with practical analysis—so assumptions are visible, tradeoffs can be discussed, and every opportunity gets the attention it deserves.</p><div className="analysis-list">{["Property valuation", "Comparable analysis", "Rental analysis", "Renovation planning", "Investment modeling"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<b>↗</b></div>)}</div><Link href="/property-analyzer" className="text-link text-link-light">Explore the property analyzer <span>↗</span></Link></div></section>
    <section className="portfolio-teaser section-pad"><div className="page-wrap"><div className="section-heading"><div><p className="eyebrow">SELECTED PROPERTIES</p><h2>Value, built <em>over time.</em></h2></div><Link href="/portfolio" className="text-link">View portfolio <span>↗</span></Link></div><div className="portfolio-empty"><div className="empty-number">S&N / PORTFOLIO</div><div><h3>Our portfolio is evolving.</h3><p>We’re building a considered collection of investments. In the meantime, learn about our approach or tell us about a property.</p><Link className="text-link" href="/sell-your-property">Start a conversation <span>↗</span></Link></div><span className="empty-corner">01 / —</span></div></div></section>
    <section className="closing-cta"><div className="page-wrap closing-inner"><div><p className="eyebrow eyebrow-light">LET’S FIND THE RIGHT NEXT STEP</p><h2>Every opportunity<br/>starts <em>with a conversation.</em></h2></div><div className="closing-links"><Link href="/sell-your-property" className="button button-cream">Sell your property <span>↗</span></Link><Link href="/invest" className="button button-outline-light">Partner with us <span>↗</span></Link></div></div></section>
  </main>;
}
