import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "../admin-shell";
import { createDeal, createProperty, setPropertyVisibility, updateDealStage, updateLeadStatus } from "../actions";
import { requireStaff } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Operations" , robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
type Row = Record<string, string | number | boolean | null | undefined>;
const leadTables = ["seller_leads","buyer_leads","investor_leads","partner_leads"] as const;
const leadLabels: Record<string,string> = { seller_leads: "Seller", buyer_leads: "Buyer", investor_leads: "Investor", partner_leads: "Partner" };
const statusOptions = [["new","New"],["contacted","Contacted"],["qualified","Qualified"],["in_progress","In progress"],["converted","Converted"],["closed","Closed"],["archived","Archived"]];

export default async function AdminSection({ params, searchParams }: { params: Promise<{ section: string }>; searchParams: Promise<{ error?: string; saved?: string }> }) {
  const { section } = await params; const query = await searchParams; const { supabase, profile } = await requireStaff();
  if (!["properties","leads","deals","analytics"].includes(section)) notFound();
  return <AdminShell name={profile.full_name}><div className="admin-heading"><div><p className="eyebrow">OPERATIONS / {section.toUpperCase()}</p><h1>{section === "properties" ? <>Property <em>management.</em></> : section === "leads" ? <>Every inquiry, <em>in view.</em></> : section === "deals" ? <>Move each deal <em>forward.</em></> : <>Activity and <em>signals.</em></>}</h1></div></div>
    {query.saved && <p className="admin-notice">Changes saved.</p>}{query.error && <p className="admin-error">{query.error === "duplicate" ? "That property URL is already in use." : query.error === "validation" ? "Please review the required fields." : "The change could not be saved. Please try again."}</p>}
    {section === "properties" && <PropertiesPanel supabase={supabase}/>}
    {section === "leads" && <LeadsPanel supabase={supabase}/>}
    {section === "deals" && <DealsPanel supabase={supabase}/>}
    {section === "analytics" && <AnalyticsPanel supabase={supabase}/>}
  </AdminShell>;
}

async function PropertiesPanel({ supabase }: { supabase: Awaited<ReturnType<typeof requireStaff>>["supabase"] }) {
  const { data } = await supabase.from("properties").select("id,title,slug,city,state,status,is_public,updated_at").order("updated_at",{ascending:false}).limit(100);
  return <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">PROPERTY RECORDS</p><h2>Properties</h2></div><span>{data?.length || 0} records</span></div>{data?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Property</th><th>Status</th><th>Visibility</th><th>Action</th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><strong>{p.title}</strong><small>{p.city}, {p.state} · /{p.slug}</small></td><td>{p.status.replaceAll("_"," ")}</td><td>{p.is_public ? "Public" : "Private"}</td><td><form action={setPropertyVisibility}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="visible" value={String(!p.is_public)}/><button className="admin-action">{p.is_public ? "Unpublish" : "Publish"}</button></form></td></tr>)}</tbody></table></div> : <div className="admin-empty"><h3>No properties yet.</h3><p>Add your first property record. Public listings require an active status and public visibility.</p></div>}</section>
  <section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">NEW RECORD</p><h2>Add a property</h2></div></div><form className="admin-form" action={createProperty}><label>Title<input name="title" required maxLength={160} placeholder="Property name"/></label><label>URL slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="cedar-avenue"/></label><div className="admin-form-grid"><label>City<input name="city" required/></label><label>State<input name="state" required maxLength={2} placeholder="CA"/></label><label>ZIP<input name="zip" maxLength={10}/></label><label>Property type<select name="propertyType"><option>Single Family</option><option>Multifamily</option><option>Commercial</option><option>Land</option><option>Other</option></select></label></div><label>Strategy<input name="strategy" placeholder="Buy & Hold, Fix & Flip…"/></label><label>Status<select name="status"><option value="lead">Lead</option><option value="under_analysis">Under analysis</option><option value="under_contract">Under contract</option><option value="renovation">Renovation</option><option value="for_sale">For sale</option><option value="for_rent">For rent</option><option value="sold">Sold</option><option value="held">Held</option></select></label><label>Description<textarea name="description" rows={4}/></label><label className="admin-checkbox"><input type="checkbox" name="isPublic"/> Allow this property to appear publicly</label><button className="button">Save property <span>↗</span></button></form></section></div>;
}

async function LeadsPanel({ supabase }: { supabase: Awaited<ReturnType<typeof requireStaff>>["supabase"] }) {
  const results = await Promise.all(leadTables.map(table=>supabase.from(table).select("*").order("created_at",{ascending:false}).limit(80)));
  const leads: (Row & { table: string })[] = [];
  results.forEach((result,index)=>{ for (const row of (result.data || []) as unknown as Row[]) leads.push({ ...row, table: leadTables[index] }); });
  leads.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))); leads.splice(120);
  return <section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">INQUIRY PIPELINE</p><h2>Recent leads</h2></div><span>{leads.length} shown</span></div>{leads.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Lead</th><th>Type</th><th>Property / interest</th><th>Status</th><th>Update</th></tr></thead><tbody>{leads.map((lead,i)=><tr key={`${lead.table}-${lead.id || i}`}><td><strong>{String(lead.name || "—")}</strong><small><a href={`mailto:${String(lead.email || "")}`}>{String(lead.email || "—")}</a>{lead.phone ? ` · ${String(lead.phone)}` : ""}</small></td><td>{leadLabels[lead.table]}</td><td>{String(lead.address || lead.interest || lead.message || "—")}</td><td>{String(lead.lead_status || "new").replaceAll("_"," ")}</td><td><form action={updateLeadStatus} className="admin-status-form"><input type="hidden" name="id" value={String(lead.id || "")}/><input type="hidden" name="table" value={lead.table}/><select name="status" defaultValue={String(lead.lead_status || "new")} aria-label="Lead status">{statusOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="admin-action">Save</button></form></td></tr>)}</tbody></table></div> : <div className="admin-empty"><h3>No leads to review.</h3><p>New website inquiries will appear here once Supabase is connected and the database migration is applied.</p></div>}</section>;
}

async function DealsPanel({ supabase }: { supabase: Awaited<ReturnType<typeof requireStaff>>["supabase"] }) {
  const [{ data: deals },{data: properties}] = await Promise.all([supabase.from("deals").select("id,title,stage,created_at,properties(title)").order("created_at",{ascending:false}).limit(100),supabase.from("properties").select("id,title").neq("status","archived").order("title")]);
  return <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">PIPELINE</p><h2>Active deals</h2></div></div>{deals?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Deal</th><th>Property</th><th>Stage</th><th>Created</th><th>Update</th></tr></thead><tbody>{deals.map(d=><tr key={d.id}><td><strong>{d.title}</strong></td><td>{Array.isArray(d.properties) ? d.properties[0]?.title || "—" : (d.properties as {title?:string}|null)?.title || "—"}</td><td>{d.stage.replaceAll("_"," ")}</td><td>{new Date(d.created_at).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"})}</td><td><form action={updateDealStage} className="admin-status-form"><input type="hidden" name="id" value={d.id}/><select name="stage" defaultValue={d.stage} aria-label="Deal stage"><option value="lead">Lead</option><option value="analysis">Analysis</option><option value="offer">Offer</option><option value="under_contract">Under contract</option><option value="renovation">Renovation</option><option value="listed">Listed</option><option value="sold">Sold</option><option value="held">Held</option></select><button className="admin-action">Save</button></form></td></tr>)}</tbody></table></div>:<div className="admin-empty"><h3>No deals in the pipeline.</h3><p>Create a deal to begin tracking it through analysis, offer, execution, and disposition.</p></div>}</section><section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">NEW RECORD</p><h2>Create a deal</h2></div></div><form className="admin-form" action={createDeal}><label>Deal name<input name="title" required maxLength={180}/></label><label>Related property<select name="propertyId"><option value="">No property linked</option>{properties?.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Stage<select name="stage"><option value="lead">Lead</option><option value="analysis">Analysis</option><option value="offer">Offer</option><option value="under_contract">Under contract</option><option value="renovation">Renovation</option><option value="listed">Listed</option><option value="sold">Sold</option><option value="held">Held</option></select></label><button className="button">Add to pipeline <span>↗</span></button></form></section></div>;
}

async function AnalyticsPanel({ supabase }: { supabase: Awaited<ReturnType<typeof requireStaff>>["supabase"] }) {
  const [properties,sellers,buyers,investors,partners,deals] = await Promise.all([
    supabase.from("properties").select("id",{count:"exact",head:true}),supabase.from("seller_leads").select("id",{count:"exact",head:true}),supabase.from("buyer_leads").select("id",{count:"exact",head:true}),supabase.from("investor_leads").select("id",{count:"exact",head:true}),supabase.from("partner_leads").select("id",{count:"exact",head:true}),supabase.from("deals").select("id",{count:"exact",head:true})
  ]);
  const counts=[["Property records",properties.count],["Seller inquiries",sellers.count],["Buyer inquiries",buyers.count],["Investor inquiries",investors.count],["Partner inquiries",partners.count],["Deals tracked",deals.count]] as const;
  return <><div className="admin-stats">{counts.map(([label,count])=><div key={label} className="admin-stat"><span>{label}</span><strong>{count ?? "—"}</strong></div>)}</div><section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">EVENT TRACKING</p><h2>Measurement, with context.</h2></div></div><p className="admin-copy">These totals come directly from operational records. Lead-source reporting, property views, conversion rates, and analyzer usage will appear after the analytics event pipeline is connected.</p><div className="admin-quicklinks"><Link href="/admin/leads">Review leads <span>↗</span></Link><Link href="/admin/properties">Review portfolio <span>↗</span></Link></div></section></>;
}
