create extension if not exists pgcrypto;

create type public.property_status as enum ('lead','under_analysis','offer_made','under_contract','renovation','for_sale','for_rent','sold','held','archived');
create type public.lead_status as enum ('new','contacted','qualified','in_progress','converted','closed','archived');
create type public.deal_stage as enum ('lead','analysis','offer','under_contract','renovation','listed','sold','held');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'staff' check (role in ('admin','staff','investor')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.markets (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, city text, state text, is_active boolean not null default false, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.properties (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, address text, city text not null, state text not null, zip text, property_type text not null, bedrooms numeric(4,1), bathrooms numeric(4,1), square_feet integer check(square_feet is null or square_feet >= 0), lot_size numeric(12,2), year_built integer, status public.property_status not null default 'lead', strategy text, description text, features text[] not null default '{}', latitude numeric(10,7), longitude numeric(10,7), is_public boolean not null default false, featured boolean not null default false, market_id uuid references public.markets(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.property_metrics (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, acquisition_price numeric(14,2), renovation_budget numeric(14,2), estimated_arv numeric(14,2), expected_rent numeric(12,2), financing jsonb not null default '{}', visibility text not null default 'private' check(visibility in ('private','public')), created_at timestamptz not null default now());
create table public.property_images (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, url text not null, alt_text text, sort_order integer not null default 0, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.property_documents (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, storage_path text not null, title text, document_type text, visibility text not null default 'private' check(visibility in ('private','public')), created_at timestamptz not null default now());
create table public.seller_leads (id uuid primary key default gen_random_uuid(), address text not null, city text not null, state text not null, zip text, property_type text, bedrooms numeric(4,1), bathrooms numeric(4,1), square_feet integer, occupancy text, condition text, situation text, photo_uploads jsonb not null default '[]', name text not null, email text not null, phone text, preferred_contact text, message text, lead_status public.lead_status not null default 'new', source text not null default 'website', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.buyer_leads (id uuid primary key default gen_random_uuid(), property_id uuid references public.properties(id) on delete set null, name text not null, email text not null, phone text, message text, lead_status public.lead_status not null default 'new', source text not null default 'website', created_at timestamptz not null default now());
create table public.investor_leads (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, interest text, message text, lead_status public.lead_status not null default 'new', source text not null default 'website', created_at timestamptz not null default now());
create table public.partner_leads (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, interest text, message text, lead_status public.lead_status not null default 'new', source text not null default 'website', created_at timestamptz not null default now());
create table public.property_analyses (id uuid primary key default gen_random_uuid(), property_id uuid references public.properties(id) on delete set null, user_id uuid references public.users(id) on delete set null, assumptions jsonb not null, results jsonb not null, provider text not null default 'manual', created_at timestamptz not null default now());
create table public.deals (id uuid primary key default gen_random_uuid(), property_id uuid references public.properties(id) on delete set null, title text not null, stage public.deal_stage not null default 'lead', assigned_to uuid references public.users(id) on delete set null, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.deal_events (id uuid primary key default gen_random_uuid(), deal_id uuid not null references public.deals(id) on delete cascade, actor_id uuid references public.users(id) on delete set null, event_type text not null, details jsonb not null default '{}', created_at timestamptz not null default now());
create table public.market_metrics (id uuid primary key default gen_random_uuid(), market_id uuid not null references public.markets(id) on delete cascade, metric_key text not null, value numeric, period date, provider text, visibility text not null default 'private' check(visibility in ('private','public')), created_at timestamptz not null default now());
create table public.saved_properties (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, created_at timestamptz not null default now(), unique(user_id,property_id));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, details jsonb not null default '{}', created_at timestamptz not null default now());

create index properties_status_idx on public.properties(status); create index properties_market_idx on public.properties(city,state); create index properties_type_idx on public.properties(property_type); create index properties_strategy_idx on public.properties(strategy); create index properties_public_idx on public.properties(is_public,featured); create index seller_leads_status_created_idx on public.seller_leads(lead_status,created_at desc); create index seller_leads_location_idx on public.seller_leads(city,state); create index investor_leads_status_created_idx on public.investor_leads(lead_status,created_at desc); create index partner_leads_status_created_idx on public.partner_leads(lead_status,created_at desc); create index deals_stage_idx on public.deals(stage,created_at desc); create index market_metrics_lookup_idx on public.market_metrics(market_id,metric_key,period desc); create index audit_logs_created_idx on public.audit_logs(created_at desc);

alter table public.users enable row level security; alter table public.markets enable row level security; alter table public.properties enable row level security; alter table public.property_metrics enable row level security; alter table public.property_images enable row level security; alter table public.property_documents enable row level security; alter table public.seller_leads enable row level security; alter table public.buyer_leads enable row level security; alter table public.investor_leads enable row level security; alter table public.partner_leads enable row level security; alter table public.property_analyses enable row level security; alter table public.deals enable row level security; alter table public.deal_events enable row level security; alter table public.market_metrics enable row level security; alter table public.saved_properties enable row level security; alter table public.audit_logs enable row level security;

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.users where id = auth.uid() and role in ('admin','staff')); $$;
create policy "Users can read their own profile" on public.users for select using (id=auth.uid() or public.is_staff());
create policy "Staff manage user profiles" on public.users for all using (public.is_staff()) with check (public.is_staff());
create policy "Public can read active markets" on public.markets for select using (is_active or public.is_staff());
create policy "Public can read published properties" on public.properties for select using ((is_public and status in ('for_sale','for_rent','sold','held')) or public.is_staff());
create policy "Public can read published property images" on public.property_images for select using (exists(select 1 from public.properties p where p.id=property_id and p.is_public) or public.is_staff());
create policy "Staff manage markets" on public.markets for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage properties" on public.properties for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage property data" on public.property_metrics for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage images" on public.property_images for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage documents" on public.property_documents for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage seller leads" on public.seller_leads for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage buyer leads" on public.buyer_leads for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage investor leads" on public.investor_leads for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage partner leads" on public.partner_leads for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage analyses" on public.property_analyses for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage deals" on public.deals for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff manage deal events" on public.deal_events for all using (public.is_staff()) with check (public.is_staff());
create policy "Staff read market metrics" on public.market_metrics for select using ((visibility='public') or public.is_staff());
create policy "Staff manage market metrics" on public.market_metrics for all using (public.is_staff()) with check (public.is_staff());
create policy "Users manage own saved properties" on public.saved_properties for all using (user_id=auth.uid() or public.is_staff()) with check (user_id=auth.uid() or public.is_staff());
create policy "Staff read audit logs" on public.audit_logs for select using (public.is_staff());
create policy "Staff write audit logs" on public.audit_logs for insert with check (public.is_staff());

-- Public lead submissions are accepted only through the server API using a service role key.
-- Never expose that key to browser code. No anonymous table-write policy is created.
