import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { LeadForm, Analyzer } from "@/components/forms";
import { getPublicProperties, getPublicProperty } from "@/lib/properties";
import { PropertyDetail, PropertyGrid } from "@/components/property-list";

const pages: Record<string, { title: string; italic?: string; eyebrow: string; description: string; kind?: string }> = {
  about: { title: "A disciplined approach", italic: "to real estate.", eyebrow: "ABOUT STABLE & NOBLE", description: "Stable & Noble Properties is a real estate investment company focused on thoughtful acquisition, improvement, and operations." },
  "what-we-do": { title: "A property deserves", italic: "a clear plan.", eyebrow: "WHAT WE DO", description: "We evaluate opportunities with care, execute with intention, and stay focused on the fundamentals that support long-term value." },
  acquisitions: { title: "Find the right", italic: "opportunity.", eyebrow: "ACQUISITIONS", description: "We look beyond the listing to understand the asset, the market, and the assumptions behind an acquisition." },
  renovation: { title: "Improve with", italic: "purpose.", eyebrow: "RENOVATION & TRANSFORMATION", description: "Our improvement strategy begins with the needs of the property and a clear view of the work required to create value." },
  operations: { title: "Built to perform", italic: "over time.", eyebrow: "OPERATIONS", description: "Sound operations connect the investment thesis to the day-to-day decisions that support a property’s long-term potential." },
  "property-sales": { title: "A thoughtful path", italic: "to market.", eyebrow: "PROPERTY SALES", description: "When a property is ready for its next chapter, we bring a considered perspective to positioning and disposition." },
  partnerships: { title: "Better outcomes,", italic: "built together.", eyebrow: "PARTNERSHIPS", description: "We value lasting relationships with owners, lenders, investors, agents, contractors, and local experts." },
  portfolio: { title: "A considered", italic: "collection.", eyebrow: "PORTFOLIO", description: "Our portfolio is evolving. Explore our investment approach or contact us about a property opportunity." },
  "sell-your-property": { title: "Have a property", italic: "to sell?", eyebrow: "SELL YOUR PROPERTY", description: "Tell us a little about your property and your plans. Our team will review the opportunity and follow up with you.", kind: "seller" },
  invest: { title: "Partnership starts", italic: "with a conversation.", eyebrow: "INVEST & PARTNER", description: "We welcome thoughtful conversations with private lenders and strategic real estate partners. Share what you have in mind and we’ll follow up.", kind: "investor" },
  "invest/partners": { title: "Aligned partners.", italic: "Clear expectations.", eyebrow: "STRATEGIC PARTNERSHIPS", description: "We work with partners who value direct communication, careful underwriting, and thoughtful execution.", kind: "investor" },
  insights: { title: "Ideas for a more", italic: "informed market.", eyebrow: "INSIGHTS", description: "Practical perspectives on property analysis, real estate investing, market context, and technology." },
  contact: { title: "Start a", italic: "conversation.", eyebrow: "CONTACT", description: "Tell us what you’re working on. We’ll make sure your message reaches the right person.", kind: "contact" },
  privacy: { title: "Privacy", italic: "policy.", eyebrow: "LEGAL", description: "This page is a framework for Stable & Noble Properties’ privacy practices and should be reviewed by legal counsel before publication." },
  terms: { title: "Terms of", italic: "use.", eyebrow: "LEGAL", description: "Use of this website is subject to the terms described here. Final legal terms should be reviewed by counsel." },
  disclosures: { title: "Important", italic: "disclosures.", eyebrow: "LEGAL", description: "Information on this site is general in nature and should not be interpreted as an offer or advice." },
  "property-analyzer": { title: "Analyze a", italic: "property.", eyebrow: "PROPERTY ANALYZER", description: "Make your assumptions explicit. Explore a first-pass view of rental economics and estimated project costs.", kind: "analyzer" },
  "sell-your-property/thank-you": { title: "Thank you for", italic: "getting in touch.", eyebrow: "MESSAGE RECEIVED", description: "We appreciate you sharing the details. A member of our team will follow up soon." },
  "admin": { title: "Operations", italic: "workspace.", eyebrow: "STABLE & NOBLE / INTERNAL", description: "The internal property and lead dashboard is being prepared. Connect Supabase Auth to enable secure team access." },
  "admin/properties": { title: "Property", italic: "management.", eyebrow: "ADMIN / PROPERTIES", description: "Connect Supabase to create and manage internal property records." },
  "admin/leads": { title: "Lead", italic: "management.", eyebrow: "ADMIN / LEADS", description: "Connect Supabase to review and manage incoming inquiries." },
  "admin/deals": { title: "Deal", italic: "pipeline.", eyebrow: "ADMIN / DEALS", description: "Connect Supabase to manage deals from initial lead through hold or disposition." },
  "admin/analytics": { title: "Business", italic: "intelligence.", eyebrow: "ADMIN / ANALYTICS", description: "Connect analytics providers to view property engagement, lead sources, and conversion activity." }
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }): Promise<Metadata> {
  const { slug } = await params;
  if (slug[0] === "portfolio" && slug.length === 2) { const property = await getPublicProperty(slug[1]); if (property) return { title: property.title, description: property.description || `${property.property_type} investment property in ${property.city}, ${property.state}.` }; }
  const item = pages[slug.join("/")] || (slug[0] === "markets" && slug.length === 2 ? { title: `${slug[1].replaceAll("-", " ")} market`, description: "Market information is not currently available. Contact Stable & Noble Properties for current investment criteria." } : null);
  return item ? { title: `${item.title} ${item.italic || ""}`, description: item.description } : {};
}

export default async function ContentPage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params; const key = slug.join("/"); const page = pages[key] || (slug[0] === "markets" && slug.length === 2 ? { title: slug[1].replaceAll("-", " "), italic: "market.", eyebrow: "MARKET PAGE", description: "Market information is not currently available. Our geographic focus is configurable and should be confirmed before publication." } : slug[0] === "portfolio" && slug.length === 2 ? { title: "Property details", italic: "coming soon.", eyebrow: "PORTFOLIO / PROPERTY", description: "This property is not currently available for public viewing." } : slug[0] === "insights" && slug.length === 2 ? { title: "Insight", italic: "coming soon.", eyebrow: "INSIGHTS", description: "This article is not currently available." } : null);
  if (!page) notFound();
  const property = slug[0] === "portfolio" && slug.length === 2 ? await getPublicProperty(slug[1]) : null;
  const publicProperties = key === "portfolio" ? await getPublicProperties() : [];
  const serviceIndex = ["acquisitions", "renovation", "operations", "property-sales", "partnerships"].indexOf(slug.at(-1) || "");
  const legal = ["privacy", "terms", "disclosures"].includes(key);
  return <main><section className="inner-hero"><div className="page-wrap inner-hero-content"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}<br/><em>{page.italic}</em></h1><p className="inner-intro">{page.description}</p></div><div className="inner-hero-bottom"><span>STABLE & NOBLE PROPERTIES</span><span>{slug.map(s => s.toUpperCase()).join(" / ")}</span></div></section>
    {page.kind === "analyzer" ? <section className="section-pad"><div className="page-wrap"><Analyzer/><p className="disclaimer">This analysis is for informational purposes only and does not constitute financial, investment, legal, tax, or real estate advice. Estimates use only values entered by you, are not guaranteed, and should be independently verified.</p></div></section> : null}
    {page.kind ? page.kind !== "analyzer" && <section className="section-pad form-section"><div className="page-wrap form-layout"><div className="form-aside"><p className="eyebrow">{page.kind === "seller" ? "PROPERTY INQUIRY" : page.kind === "investor" ? "PARTNER INQUIRY" : "SEND A NOTE"}</p><h2>{page.kind === "seller" ? <>Tell us about<br/><em>the property.</em></> : <>Good work begins<br/><em>with a note.</em></>}</h2><p>We’ll review your message and follow up using the contact information you provide.</p><div className="aside-contact"><span>DIRECT & THOUGHTFUL</span><p>Every conversation starts with listening and understanding the opportunity.</p></div></div><div className="form-card"><LeadForm kind={page.kind as "seller" | "investor" | "contact"}/></div></div></section> : null}
    {!page.kind && key === "portfolio" && <section className="section-pad"><div className="page-wrap">{publicProperties.length ? <PropertyGrid properties={publicProperties}/> : <div className="portfolio-empty portfolio-page-empty"><div className="empty-number">S&N / PORTFOLIO</div><div><h3>Our portfolio is evolving.</h3><p>As opportunities develop, this is where we’ll share selected properties and projects. We don’t publish private property information.</p><Link className="text-link" href="/what-we-do">Explore our investment approach <span>↗</span></Link></div></div>}</div></section>}
    {!page.kind && key.startsWith("portfolio/") && (property ? <PropertyDetail property={property}/> : <section className="section-pad"><div className="page-wrap"><p className="lead">This property is not currently available for public viewing.</p><Link className="text-link" href="/portfolio">Return to portfolio <span>↗</span></Link></div></section>)}
    {!page.kind && key === "about" && <section className="section-pad"><div className="page-wrap content-grid"><div><p className="eyebrow">INVESTMENT PHILOSOPHY</p><h2>Look closely.<br/><em>Act deliberately.</em></h2></div><div className="body-copy"><p className="lead">Each property has its own context. We take time to understand the fundamentals before deciding whether an opportunity is right for us.</p><p>Our process considers location, market fundamentals, condition, acquisition economics, renovation potential, rental economics, exit opportunities, and long-term value. We aim to communicate clearly and make considered decisions at every stage.</p><p className="eyebrow">AHMED MUSTAPHA · FOUNDER & REAL ESTATE INVESTOR</p><p>Stable & Noble Properties is led by founder Ahmed Mustapha. More company and founder information will be shared here as the firm’s story develops.</p></div></div></section>}
    {!page.kind && ["what-we-do", "acquisitions", "renovation", "operations", "partnerships", "property-sales"].includes(slug.at(-1) || "") && <section className="section-pad"><div className="page-wrap service-block"><p className="eyebrow">THE WORK, IN PRACTICE</p><h2>{serviceIndex < 0 ? "Four disciplines. One point of view." : ["Start with fundamentals.", "Improve what matters.", "Care in every detail.", "A considered next chapter.", "Relationships that compound."][serviceIndex]}</h2><p className="lead">{serviceIndex < 0 ? "Acquisition, transformation, operations, and partnership each play a part in our approach to real estate." : page.description}</p><div className="service-links">{[["Acquisitions", "/what-we-do/acquisitions"],["Renovation", "/what-we-do/renovation"],["Operations", "/what-we-do/operations"],["Property sales", "/what-we-do/property-sales"],["Partnerships", "/what-we-do/partnerships"]].map(([x,y])=><Link key={x} href={y}><span>{x}</span><b>↗</b></Link>)}</div></div></section>}
    {key === "invest" && <section className="disclosure-band"><div className="page-wrap"><p>All investment discussions are exploratory. This website does not constitute an offer to sell or a solicitation to buy any security or investment product. No returns are guaranteed. Any future offering would be made only through appropriate documentation and in accordance with applicable law.</p></div></section>}
    {key === "insights" && <section className="section-pad"><div className="page-wrap insights-empty"><p className="eyebrow">EDITORIAL NOTEBOOK</p><h2>Thoughtful perspectives.<br/><em>Grounded in practice.</em></h2><p>New insights are in development. Topics will include property analysis, seller resources, market context, renovation, and real estate technology.</p><div className="topic-row">{["Property analysis", "Seller resources", "Market insights", "Renovation", "Real estate technology"].map(x=><span key={x}>{x}</span>)}</div></div></section>}
    {legal && <section className="section-pad"><div className="page-wrap legal-content"><h2>Website information</h2><p>This website is provided for general informational purposes. Information may change without notice and is not a substitute for professional advice tailored to your circumstances.</p><h2>Data and communication</h2><p>If you submit a form, Stable & Noble Properties may use the information you provide to respond to your request and maintain business records. Do not send confidential or sensitive financial information through this website.</p><h2>Property analysis and investment</h2><p>Any calculations or property information are illustrative, depend on user-entered assumptions, and are not guaranteed. Nothing on this site is financial, investment, legal, tax, lending, or real estate advice or an offer to participate in an investment.</p><p className="fine-print">This is placeholder legal content and must be reviewed and replaced by qualified counsel before launch.</p></div></section>}
    {key !== "invest" && <section className="small-cta"><div className="page-wrap"><p>Have an opportunity in mind?</p><Link href="/contact" className="text-link">Let’s talk <span>↗</span></Link></div></section>}
  </main>;
}
